# Generated by Django 4.0.4 on 2022-06-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_post_author_remove_post_likes_project_likes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
