# Generated by Django 4.0.2 on 2022-03-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_content_comment_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
